INSERT INTO DB_GO_CURSO.CLIENTES (NOMBRE, CORREO, TELEFONO, FECHA)
VALUES('JUAN LOPEZ', 'juan.lopez@micorreo.com', '55555555555', SYSDATE());

INSERT INTO DB_GO_CURSO.CLIENTES (NOMBRE, CORREO, TELEFONO, FECHA)
VALUES('FELIPE FUENTES', 'felipe.fuentes@micorreo.com', '55555555555', SYSDATE());

INSERT INTO DB_GO_CURSO.CLIENTES (NOMBRE, CORREO, TELEFONO, FECHA)
VALUES('HUMBERTO MEDINA', 'humberto.medina@micorreo.com', '55555555555', SYSDATE());

INSERT INTO DB_GO_CURSO.CLIENTES (NOMBRE, CORREO, TELEFONO, FECHA)
VALUES('RAFAEL MARQUEZ', 'rafael.marquez@micorreo.com', '55555555555', SYSDATE());

INSERT INTO DB_GO_CURSO.CLIENTES (NOMBRE, CORREO, TELEFONO, FECHA)
VALUES('JAVIER SOL', 'javier.solis@micorreo.com', '55555555555', SYSDATE());