CREATE TABLE CLIENTES(

	ID INT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(100) NOT NULL,
	CORREO VARCHAR(100) NOT NULL,
	TELEFONO VARCHAR(20) NOT NULL,
	FECHA DATETIME NOT NULL,
	
	PRIMARY KEY (ID)
)


CREATE TABLE USUARIOS(

	ID INT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(100) NOT NULL,
	CORREO VARCHAR(100) NOT NULL,
	TELEFONO VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	
	PRIMARY KEY (ID)
)